image:
  name: nvcr.io/nvidia/physicsnemo/physicsnemo:25.03
  entrypoint: [""]

stages:
  - build
  - test

lint:
  stage: build

  before_script:
    - pip install -e .[dev] --no-build-isolation
    - pip install pre-commit --no-build-isolation

  script:
    - pre-commit run --all-files

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

unit_tests:
  stage: test

  before_script:
    - pip install -e .[dev] --no-build-isolation

  script:
    - pytest ./tests

  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
