source:
  class: VTKSource
  module: physicsnemo_curator.mesh.sources.vtk
  name: VTK Reader
  description: Read VTK files (.vtk, .vtp, .vtu, .vts, .vtm) and convert to physicsnemo
    Mesh
  params:
    store: LocalFileStore(root=PosixPath('test'), files=1)
    manifold_dim: '2'
    point_source: vertices
    warn_on_lost_data: 'True'
    backend: rust
filters: []
sink:
  class: MeshSink
  module: physicsnemo_curator.mesh.sinks.mesh_writer
  name: PhysicsNeMo Mesh Writer
  description: Save meshes in physicsnemo native format (tensordict memmap)
  params:
    output_dir: output
    naming_template: None
    source_store: null
version: 1
